requires = ["tox>=4.25"]
env_list = [
    { product = [["py"], ["aiohttp", "httpx", "niquests", "pyreqwest", "all", "pinned"], ["", "noreactor"]] },
    "pre-commit",
    "typing",
    "twinecheck",
]

[env_run_base]
pass_env = [
    "PYTEST_ADDOPTS",
]
deps = [
    "pytest>=9",
    "pytest-cov>=7.0.0",
    "pytest-xdist>=3.7.0",
    "Twisted[http2]>=25.5.0",
    { replace = "if", condition = "not factor.noreactor", then = ["pytest-twisted"], extend = true },
    { replace = "if", condition = "factor.noreactor", then = ["pytest-asyncio"], extend = true },
    { replace = "if", condition = "factor.pinned", then = [
        "aiohttp==3.11.0",
        "httpx[http2]==0.28.1",
        "niquests==3.18.6",
        "pyreqwest==0.11.0;python_version >= '3.11'",  # the easiest is to skip this on CI
    ], extend = true },
]
extras = [
    { replace = "if", condition = "factor.all or factor.aiohttp", then = ["aiohttp"], extend = true },
    { replace = "if", condition = "factor.all or factor.httpx", then = ["httpx"], extend = true },
    { replace = "if", condition = "factor.all or factor.niquests", then = ["niquests"], extend = true },
    { replace = "if", condition = "factor.all or factor.pyreqwest", then = ["pyreqwest"], extend = true },
]
commands = [
    [
        "pytest",
        { replace = "posargs", default = [
            "--cov-config=pyproject.toml",
            "--cov=scrapy_download_handlers_incubator",
            "--cov-report=term-missing",
            "--cov-report=xml",
            "--junitxml={env_name}.junit.xml",
            "-o",
            "junit_family=legacy",
            "tests",
        ], extend = true },
        { replace = "if", condition = "not factor.noreactor", then = ["--reactor=asyncio"], extend = true },
    ],
]

[env.pre-commit]
deps = [
    "pre-commit",
]
commands = [
    ["pre-commit", "run", { replace = "posargs", default = ["--all-files"], extend = true }],
]

[env.typing]
deps = [
    "mypy==1.20.0",
    "aiohttp==3.13.5",
    "httpx[http2]==0.28.1",
    "niquests==3.18.6",
    "pyreqwest==0.11.6",
    "pytest==9.0.2",
    "Scrapy==2.15.0",
]
commands = [
    ["mypy", { replace = "posargs", default = ["src", "tests"], extend = true }],
]

[env.twinecheck]
deps = [
    "twine==6.2.0",
    "build==1.4.2",
]
commands = [
    ["python", "-m", "build", "--sdist"],
    ["twine", "check", "dist/*"],
]
